//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.04 at 11:29:01 AM IST 
//

package com.nordea.assessment.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CreditTransferTransaction26 complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CreditTransferTransaction26"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PmtId" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}PaymentIdentification1"/&gt;
 *         &lt;element name="PmtTpInf" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}PaymentTypeInformation19" minOccurs="0"/&gt;
 *         &lt;element name="Amt" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}AmountType4Choice"/&gt;
 *         &lt;element name="XchgRateInf" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}ExchangeRate1" minOccurs="0"/&gt;
 *         &lt;element name="ChrgBr" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}ChargeBearerType1Code" minOccurs="0"/&gt;
 *         &lt;element name="ChqInstr" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}Cheque7" minOccurs="0"/&gt;
 *         &lt;element name="UltmtDbtr" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}PartyIdentification43" minOccurs="0"/&gt;
 *         &lt;element name="IntrmyAgt1" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}BranchAndFinancialInstitutionIdentification5" minOccurs="0"/&gt;
 *         &lt;element name="IntrmyAgt1Acct" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}CashAccount24" minOccurs="0"/&gt;
 *         &lt;element name="IntrmyAgt2" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}BranchAndFinancialInstitutionIdentification5" minOccurs="0"/&gt;
 *         &lt;element name="IntrmyAgt2Acct" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}CashAccount24" minOccurs="0"/&gt;
 *         &lt;element name="IntrmyAgt3" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}BranchAndFinancialInstitutionIdentification5" minOccurs="0"/&gt;
 *         &lt;element name="IntrmyAgt3Acct" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}CashAccount24" minOccurs="0"/&gt;
 *         &lt;element name="CdtrAgt" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}BranchAndFinancialInstitutionIdentification5" minOccurs="0"/&gt;
 *         &lt;element name="CdtrAgtAcct" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}CashAccount24" minOccurs="0"/&gt;
 *         &lt;element name="Cdtr" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}PartyIdentification43" minOccurs="0"/&gt;
 *         &lt;element name="CdtrAcct" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}CashAccount24" minOccurs="0"/&gt;
 *         &lt;element name="UltmtCdtr" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}PartyIdentification43" minOccurs="0"/&gt;
 *         &lt;element name="InstrForCdtrAgt" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}InstructionForCreditorAgent1" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="InstrForDbtrAgt" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}Max140Text" minOccurs="0"/&gt;
 *         &lt;element name="Purp" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}Purpose2Choice" minOccurs="0"/&gt;
 *         &lt;element name="RgltryRptg" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}RegulatoryReporting3" maxOccurs="10" minOccurs="0"/&gt;
 *         &lt;element name="Tax" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}TaxInformation3" minOccurs="0"/&gt;
 *         &lt;element name="RltdRmtInf" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}RemittanceLocation4" maxOccurs="10" minOccurs="0"/&gt;
 *         &lt;element name="RmtInf" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}RemittanceInformation11" minOccurs="0"/&gt;
 *         &lt;element name="SplmtryData" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}SupplementaryData1" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditTransferTransaction26", propOrder = { "PmtId", "PmtTpInf", "Amt", "XchgRateInf", "ChrgBr",
		"ChqInstr", "UltmtDbtr", "IntrmyAgt1", "IntrmyAgt1Acct", "IntrmyAgt2", "IntrmyAgt2Acct", "IntrmyAgt3",
		"IntrmyAgt3Acct", "CdtrAgt", "CdtrAgtAcct", "Cdtr", "CdtrAcct", "UltmtCdtr", "InstrForCdtrAgt",
		"InstrForDbtrAgt", "Purp", "RgltryRptg", "Tax", "RltdRmtInf", "RmtInf", "SplmtryData" })
public class CreditTransferTransaction26 {

	@XmlElement(name = "PmtId", required = true)
	protected PaymentIdentification1 PmtId;
	@XmlElement(name = "PmtTpInf")
	protected PaymentTypeInformation19 PmtTpInf;
	@XmlElement(name = "Amt", required = true)
	protected AmountType4Choice Amt;
	@XmlElement(name = "XchgRateInf")
	protected ExchangeRate1 XchgRateInf;
	@XmlElement(name = "ChrgBr")
	@XmlSchemaType(name = "String")
	protected ChargeBearerType1Code ChrgBr;
	@XmlElement(name = "ChqInstr")
	protected Cheque7 ChqInstr;
	@XmlElement(name = "UltmtDbtr")
	protected PartyIdentification43 UltmtDbtr;
	@XmlElement(name = "IntrmyAgt1")
	protected BranchAndFinancialInstitutionIdentification5 IntrmyAgt1;
	@XmlElement(name = "IntrmyAgt1Acct")
	protected CashAccount24 IntrmyAgt1Acct;
	@XmlElement(name = "IntrmyAgt2")
	protected BranchAndFinancialInstitutionIdentification5 IntrmyAgt2;
	@XmlElement(name = "IntrmyAgt2Acct")
	protected CashAccount24 IntrmyAgt2Acct;
	@XmlElement(name = "IntrmyAgt3")
	protected BranchAndFinancialInstitutionIdentification5 IntrmyAgt3;
	@XmlElement(name = "IntrmyAgt3Acct")
	protected CashAccount24 IntrmyAgt3Acct;
	@XmlElement(name = "CdtrAgt")
	protected BranchAndFinancialInstitutionIdentification5 CdtrAgt;
	@XmlElement(name = "CdtrAgtAcct")
	protected CashAccount24 CdtrAgtAcct;
	@XmlElement(name = "Cdtr")
	protected PartyIdentification43 Cdtr;
	@XmlElement(name = "CdtrAcct")
	protected CashAccount24 CdtrAcct;
	@XmlElement(name = "UltmtCdtr")
	protected PartyIdentification43 UltmtCdtr;
	@XmlElement(name = "InstrForCdtrAgt")
	protected List<InstructionForCreditorAgent1> InstrForCdtrAgt;
	@XmlElement(name = "InstrForDbtrAgt")
	protected String InstrForDbtrAgt;
	@XmlElement(name = "Purp")
	protected Purpose2Choice Purp;
	@XmlElement(name = "RgltryRptg")
	protected List<RegulatoryReporting3> RgltryRptg;
	@XmlElement(name = "Tax")
	protected TaxInformation3 Tax;
	@XmlElement(name = "RltdRmtInf")
	protected List<RemittanceLocation4> RltdRmtInf;
	@XmlElement(name = "RmtInf")
	protected RemittanceInformation11 RmtInf;
	@XmlElement(name = "SplmtryData")
	protected List<SupplementaryData1> SplmtryData;

	/**
	 * Gets the value of the pmtId property.
	 * 
	 * @return possible object is {@link PaymentIdentification1 }
	 * 
	 */
	public PaymentIdentification1 getPmtId() {
		return PmtId;
	}

	/**
	 * Sets the value of the pmtId property.
	 * 
	 * @param value allowed object is {@link PaymentIdentification1 }
	 * 
	 */
	public void setPmtId(PaymentIdentification1 value) {
		this.PmtId = value;
	}

	/**
	 * Gets the value of the pmtTpInf property.
	 * 
	 * @return possible object is {@link PaymentTypeInformation19 }
	 * 
	 */
	public PaymentTypeInformation19 getPmtTpInf() {
		return PmtTpInf;
	}

	/**
	 * Sets the value of the pmtTpInf property.
	 * 
	 * @param value allowed object is {@link PaymentTypeInformation19 }
	 * 
	 */
	public void setPmtTpInf(PaymentTypeInformation19 value) {
		this.PmtTpInf = value;
	}

	/**
	 * Gets the value of the amt property.
	 * 
	 * @return possible object is {@link AmountType4Choice }
	 * 
	 */
	public AmountType4Choice getAmt() {
		return Amt;
	}

	/**
	 * Sets the value of the amt property.
	 * 
	 * @param value allowed object is {@link AmountType4Choice }
	 * 
	 */
	public void setAmt(AmountType4Choice value) {
		this.Amt = value;
	}

	/**
	 * Gets the value of the xchgRateInf property.
	 * 
	 * @return possible object is {@link ExchangeRate1 }
	 * 
	 */
	public ExchangeRate1 getXchgRateInf() {
		return XchgRateInf;
	}

	/**
	 * Sets the value of the xchgRateInf property.
	 * 
	 * @param value allowed object is {@link ExchangeRate1 }
	 * 
	 */
	public void setXchgRateInf(ExchangeRate1 value) {
		this.XchgRateInf = value;
	}

	/**
	 * Gets the value of the chrgBr property.
	 * 
	 * @return possible object is {@link ChargeBearerType1Code }
	 * 
	 */
	public ChargeBearerType1Code getChrgBr() {
		return ChrgBr;
	}

	/**
	 * Sets the value of the chrgBr property.
	 * 
	 * @param value allowed object is {@link ChargeBearerType1Code }
	 * 
	 */
	public void setChrgBr(ChargeBearerType1Code value) {
		this.ChrgBr = value;
	}

	/**
	 * Gets the value of the chqInstr property.
	 * 
	 * @return possible object is {@link Cheque7 }
	 * 
	 */
	public Cheque7 getChqInstr() {
		return ChqInstr;
	}

	/**
	 * Sets the value of the chqInstr property.
	 * 
	 * @param value allowed object is {@link Cheque7 }
	 * 
	 */
	public void setChqInstr(Cheque7 value) {
		this.ChqInstr = value;
	}

	/**
	 * Gets the value of the ultmtDbtr property.
	 * 
	 * @return possible object is {@link PartyIdentification43 }
	 * 
	 */
	public PartyIdentification43 getUltmtDbtr() {
		return UltmtDbtr;
	}

	/**
	 * Sets the value of the ultmtDbtr property.
	 * 
	 * @param value allowed object is {@link PartyIdentification43 }
	 * 
	 */
	public void setUltmtDbtr(PartyIdentification43 value) {
		this.UltmtDbtr = value;
	}

	/**
	 * Gets the value of the intrmyAgt1 property.
	 * 
	 * @return possible object is
	 *         {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public BranchAndFinancialInstitutionIdentification5 getIntrmyAgt1() {
		return IntrmyAgt1;
	}

	/**
	 * Sets the value of the intrmyAgt1 property.
	 * 
	 * @param value allowed object is
	 *              {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public void setIntrmyAgt1(BranchAndFinancialInstitutionIdentification5 value) {
		this.IntrmyAgt1 = value;
	}

	/**
	 * Gets the value of the intrmyAgt1Acct property.
	 * 
	 * @return possible object is {@link CashAccount24 }
	 * 
	 */
	public CashAccount24 getIntrmyAgt1Acct() {
		return IntrmyAgt1Acct;
	}

	/**
	 * Sets the value of the intrmyAgt1Acct property.
	 * 
	 * @param value allowed object is {@link CashAccount24 }
	 * 
	 */
	public void setIntrmyAgt1Acct(CashAccount24 value) {
		this.IntrmyAgt1Acct = value;
	}

	/**
	 * Gets the value of the intrmyAgt2 property.
	 * 
	 * @return possible object is
	 *         {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public BranchAndFinancialInstitutionIdentification5 getIntrmyAgt2() {
		return IntrmyAgt2;
	}

	/**
	 * Sets the value of the intrmyAgt2 property.
	 * 
	 * @param value allowed object is
	 *              {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public void setIntrmyAgt2(BranchAndFinancialInstitutionIdentification5 value) {
		this.IntrmyAgt2 = value;
	}

	/**
	 * Gets the value of the intrmyAgt2Acct property.
	 * 
	 * @return possible object is {@link CashAccount24 }
	 * 
	 */
	public CashAccount24 getIntrmyAgt2Acct() {
		return IntrmyAgt2Acct;
	}

	/**
	 * Sets the value of the intrmyAgt2Acct property.
	 * 
	 * @param value allowed object is {@link CashAccount24 }
	 * 
	 */
	public void setIntrmyAgt2Acct(CashAccount24 value) {
		this.IntrmyAgt2Acct = value;
	}

	/**
	 * Gets the value of the intrmyAgt3 property.
	 * 
	 * @return possible object is
	 *         {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public BranchAndFinancialInstitutionIdentification5 getIntrmyAgt3() {
		return IntrmyAgt3;
	}

	/**
	 * Sets the value of the intrmyAgt3 property.
	 * 
	 * @param value allowed object is
	 *              {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public void setIntrmyAgt3(BranchAndFinancialInstitutionIdentification5 value) {
		this.IntrmyAgt3 = value;
	}

	/**
	 * Gets the value of the intrmyAgt3Acct property.
	 * 
	 * @return possible object is {@link CashAccount24 }
	 * 
	 */
	public CashAccount24 getIntrmyAgt3Acct() {
		return IntrmyAgt3Acct;
	}

	/**
	 * Sets the value of the intrmyAgt3Acct property.
	 * 
	 * @param value allowed object is {@link CashAccount24 }
	 * 
	 */
	public void setIntrmyAgt3Acct(CashAccount24 value) {
		this.IntrmyAgt3Acct = value;
	}

	/**
	 * Gets the value of the cdtrAgt property.
	 * 
	 * @return possible object is
	 *         {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public BranchAndFinancialInstitutionIdentification5 getCdtrAgt() {
		return CdtrAgt;
	}

	/**
	 * Sets the value of the cdtrAgt property.
	 * 
	 * @param value allowed object is
	 *              {@link BranchAndFinancialInstitutionIdentification5 }
	 * 
	 */
	public void setCdtrAgt(BranchAndFinancialInstitutionIdentification5 value) {
		this.CdtrAgt = value;
	}

	/**
	 * Gets the value of the cdtrAgtAcct property.
	 * 
	 * @return possible object is {@link CashAccount24 }
	 * 
	 */
	public CashAccount24 getCdtrAgtAcct() {
		return CdtrAgtAcct;
	}

	/**
	 * Sets the value of the cdtrAgtAcct property.
	 * 
	 * @param value allowed object is {@link CashAccount24 }
	 * 
	 */
	public void setCdtrAgtAcct(CashAccount24 value) {
		this.CdtrAgtAcct = value;
	}

	/**
	 * Gets the value of the cdtr property.
	 * 
	 * @return possible object is {@link PartyIdentification43 }
	 * 
	 */
	public PartyIdentification43 getCdtr() {
		return Cdtr;
	}

	/**
	 * Sets the value of the cdtr property.
	 * 
	 * @param value allowed object is {@link PartyIdentification43 }
	 * 
	 */
	public void setCdtr(PartyIdentification43 value) {
		this.Cdtr = value;
	}

	/**
	 * Gets the value of the cdtrAcct property.
	 * 
	 * @return possible object is {@link CashAccount24 }
	 * 
	 */
	public CashAccount24 getCdtrAcct() {
		return CdtrAcct;
	}

	/**
	 * Sets the value of the cdtrAcct property.
	 * 
	 * @param value allowed object is {@link CashAccount24 }
	 * 
	 */
	public void setCdtrAcct(CashAccount24 value) {
		this.CdtrAcct = value;
	}

	/**
	 * Gets the value of the ultmtCdtr property.
	 * 
	 * @return possible object is {@link PartyIdentification43 }
	 * 
	 */
	public PartyIdentification43 getUltmtCdtr() {
		return UltmtCdtr;
	}

	/**
	 * Sets the value of the ultmtCdtr property.
	 * 
	 * @param value allowed object is {@link PartyIdentification43 }
	 * 
	 */
	public void setUltmtCdtr(PartyIdentification43 value) {
		this.UltmtCdtr = value;
	}

	/**
	 * Gets the value of the instrForCdtrAgt property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the instrForCdtrAgt property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getInstrForCdtrAgt().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link InstructionForCreditorAgent1 }
	 * 
	 * 
	 */
	public List<InstructionForCreditorAgent1> getInstrForCdtrAgt() {
		if (InstrForCdtrAgt == null) {
			InstrForCdtrAgt = new ArrayList<InstructionForCreditorAgent1>();
		}
		return this.InstrForCdtrAgt;
	}

	/**
	 * Gets the value of the instrForDbtrAgt property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInstrForDbtrAgt() {
		return InstrForDbtrAgt;
	}

	/**
	 * Sets the value of the instrForDbtrAgt property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setInstrForDbtrAgt(String value) {
		this.InstrForDbtrAgt = value;
	}

	/**
	 * Gets the value of the purp property.
	 * 
	 * @return possible object is {@link Purpose2Choice }
	 * 
	 */
	public Purpose2Choice getPurp() {
		return Purp;
	}

	/**
	 * Sets the value of the purp property.
	 * 
	 * @param value allowed object is {@link Purpose2Choice }
	 * 
	 */
	public void setPurp(Purpose2Choice value) {
		this.Purp = value;
	}

	/**
	 * Gets the value of the rgltryRptg property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the rgltryRptg property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRgltryRptg().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link RegulatoryReporting3 }
	 * 
	 * 
	 */

	public List<RegulatoryReporting3> getRgltryRptg() {
		if (RgltryRptg == null) {
			RgltryRptg = new ArrayList<RegulatoryReporting3>();
		}
		return this.RgltryRptg;
	}

	/**
	 * Gets the value of the tax property.
	 * 
	 * @return possible object is {@link TaxInformation3 }
	 * 
	 */
	public TaxInformation3 getTax() {
		return Tax;
	}

	/**
	 * Sets the value of the tax property.
	 * 
	 * @param value allowed object is {@link TaxInformation3 }
	 * 
	 */
	public void setTax(TaxInformation3 value) {
		this.Tax = value;
	}

	/**
	 * Gets the value of the rltdRmtInf property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the rltdRmtInf property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRltdRmtInf().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link RemittanceLocation4 }
	 * 
	 * 
	 */
	public List<RemittanceLocation4> getRltdRmtInf() {
		if (RltdRmtInf == null) {
			RltdRmtInf = new ArrayList<RemittanceLocation4>();
		}
		return this.RltdRmtInf;
	}

	/**
	 * Gets the value of the rmtInf property.
	 * 
	 * @return possible object is {@link RemittanceInformation11 }
	 * 
	 */
	public RemittanceInformation11 getRmtInf() {
		return RmtInf;
	}

	/**
	 * Sets the value of the rmtInf property.
	 * 
	 * @param value allowed object is {@link RemittanceInformation11 }
	 * 
	 */
	public void setRmtInf(RemittanceInformation11 value) {
		this.RmtInf = value;
	}

	/**
	 * Gets the value of the splmtryData property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the splmtryData property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSplmtryData().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SupplementaryData1 }
	 * 
	 * 
	 */
	public List<SupplementaryData1> getSplmtryData() {
		if (SplmtryData == null) {
			SplmtryData = new ArrayList<SupplementaryData1>();
		}
		return this.SplmtryData;
	}

}
