//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.04 at 11:29:01 AM IST 
//

package com.nordea.assessment.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for CustomerCreditTransferInitiationV08 complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerCreditTransferInitiationV08"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GrpHdr" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}GroupHeader48"/&gt;
 *         &lt;element name="PmtInf" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}PaymentInstruction22" maxOccurs="unbounded"/&gt;
 *         &lt;element name="SplmtryData" type="{urn:iso:std:iso:20022:tech:xsd:pain.001.001.08}SupplementaryData1" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerCreditTransferInitiationV08", propOrder = { "GrpHdr", "PmtInf", "SplmtryData" })
public class CustomerCreditTransferInitiationV08 {

	@XmlElement(name = "GrpHdr", required = true)
	protected GroupHeader48 GrpHdr;
	@XmlElement(name = "PmtInf", required = true)
	protected List<PaymentInstruction22> PmtInf;
	@XmlElement(name = "SplmtryData")
	protected List<SupplementaryData1> SplmtryData;

	/**
	 * Gets the value of the grpHdr property.
	 * 
	 * @return possible object is {@link GroupHeader48 }
	 * 
	 */
	public GroupHeader48 getGrpHdr() {
		return GrpHdr;
	}

	/**
	 * Sets the value of the grpHdr property.
	 * 
	 * @param value allowed object is {@link GroupHeader48 }
	 * 
	 */
	public void setGrpHdr(GroupHeader48 value) {
		this.GrpHdr = value;
	}

	/**
	 * Gets the value of the pmtInf property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the pmtInf property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPmtInf().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link PaymentInstruction22 }
	 * 
	 * 
	 */

	public List<PaymentInstruction22> getPmtInf() {
		if (PmtInf == null) {
			PmtInf = new ArrayList<PaymentInstruction22>();
		}
		return this.PmtInf;
	}

	/**
	 * Gets the value of the splmtryData property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the splmtryData property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSplmtryData().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SupplementaryData1 }
	 * 
	 * 
	 */

	public List<SupplementaryData1> getSplmtryData() {
		if (SplmtryData == null) {
			SplmtryData = new ArrayList<SupplementaryData1>();
		}
		return this.SplmtryData;
	}

}
